In [56]:
import os
import glob
import pandas as pd
import numpy as np

files_path = "/Users/joanpeluza/Desktop/cvs/subset"
read_files = glob.glob(os.path.join(files_path, "*.csv"))

np_array_values = []
for x in read_files:
    data = pd.read_csv(x, header= 0)
    name = [os.path.basename(x)]
    if (data.iloc[0,1]) > 0.8:
        data.insert(0, 'name',name, True)
        np_array_values.append(data)

In [86]:
merge_values = np.vstack(np_array_values)
data = pd.DataFrame(merge_values)
types = "name,face, confidence, gaze_0_x, gaze_0_y, gaze_0_z, gaze_1_x, gaze_1_y, gaze_1_z, gaze_angle_x, gaze_angle_y, eye_lmk_x_0, eye_lmk_x_1, eye_lmk_x_2, eye_lmk_x_3, eye_lmk_x_4, eye_lmk_x_5, eye_lmk_x_6, eye_lmk_x_7, eye_lmk_x_8, eye_lmk_x_9, eye_lmk_x_10, eye_lmk_x_11, eye_lmk_x_12, eye_lmk_x_13, eye_lmk_x_14, eye_lmk_x_15, eye_lmk_x_16, eye_lmk_x_17, eye_lmk_x_18, eye_lmk_x_19, eye_lmk_x_20, eye_lmk_x_21, eye_lmk_x_22, eye_lmk_x_23, eye_lmk_x_24, eye_lmk_x_25, eye_lmk_x_26, eye_lmk_x_27, eye_lmk_x_28, eye_lmk_x_29, eye_lmk_x_30, eye_lmk_x_31, eye_lmk_x_32, eye_lmk_x_33, eye_lmk_x_34, eye_lmk_x_35, eye_lmk_x_36, eye_lmk_x_37, eye_lmk_x_38, eye_lmk_x_39, eye_lmk_x_40, eye_lmk_x_41, eye_lmk_x_42, eye_lmk_x_43, eye_lmk_x_44, eye_lmk_x_45, eye_lmk_x_46, eye_lmk_x_47, eye_lmk_x_48, eye_lmk_x_49, eye_lmk_x_50, eye_lmk_x_51, eye_lmk_x_52, eye_lmk_x_53, eye_lmk_x_54, eye_lmk_x_55, eye_lmk_y_0, eye_lmk_y_1, eye_lmk_y_2, eye_lmk_y_3, eye_lmk_y_4, eye_lmk_y_5, eye_lmk_y_6, eye_lmk_y_7, eye_lmk_y_8, eye_lmk_y_9, eye_lmk_y_10, eye_lmk_y_11, eye_lmk_y_12, eye_lmk_y_13, eye_lmk_y_14, eye_lmk_y_15, eye_lmk_y_16, eye_lmk_y_17, eye_lmk_y_18, eye_lmk_y_19, eye_lmk_y_20, eye_lmk_y_21, eye_lmk_y_22, eye_lmk_y_23, eye_lmk_y_24, eye_lmk_y_25, eye_lmk_y_26, eye_lmk_y_27, eye_lmk_y_28, eye_lmk_y_29, eye_lmk_y_30, eye_lmk_y_31, eye_lmk_y_32, eye_lmk_y_33, eye_lmk_y_34, eye_lmk_y_35, eye_lmk_y_36, eye_lmk_y_37, eye_lmk_y_38, eye_lmk_y_39, eye_lmk_y_40, eye_lmk_y_41, eye_lmk_y_42, eye_lmk_y_43, eye_lmk_y_44, eye_lmk_y_45, eye_lmk_y_46, eye_lmk_y_47, eye_lmk_y_48, eye_lmk_y_49, eye_lmk_y_50, eye_lmk_y_51, eye_lmk_y_52, eye_lmk_y_53, eye_lmk_y_54, eye_lmk_y_55, eye_lmk_X_0, eye_lmk_X_1, eye_lmk_X_2, eye_lmk_X_3, eye_lmk_X_4, eye_lmk_X_5, eye_lmk_X_6, eye_lmk_X_7, eye_lmk_X_8, eye_lmk_X_9, eye_lmk_X_10, eye_lmk_X_11, eye_lmk_X_12, eye_lmk_X_13, eye_lmk_X_14, eye_lmk_X_15, eye_lmk_X_16, eye_lmk_X_17, eye_lmk_X_18, eye_lmk_X_19, eye_lmk_X_20, eye_lmk_X_21, eye_lmk_X_22, eye_lmk_X_23, eye_lmk_X_24, eye_lmk_X_25, eye_lmk_X_26, eye_lmk_X_27, eye_lmk_X_28, eye_lmk_X_29, eye_lmk_X_30, eye_lmk_X_31, eye_lmk_X_32, eye_lmk_X_33, eye_lmk_X_34, eye_lmk_X_35, eye_lmk_X_36, eye_lmk_X_37, eye_lmk_X_38, eye_lmk_X_39, eye_lmk_X_40, eye_lmk_X_41, eye_lmk_X_42, eye_lmk_X_43, eye_lmk_X_44, eye_lmk_X_45, eye_lmk_X_46, eye_lmk_X_47, eye_lmk_X_48, eye_lmk_X_49, eye_lmk_X_50, eye_lmk_X_51, eye_lmk_X_52, eye_lmk_X_53, eye_lmk_X_54, eye_lmk_X_55, eye_lmk_Y_0, eye_lmk_Y_1, eye_lmk_Y_2, eye_lmk_Y_3, eye_lmk_Y_4, eye_lmk_Y_5, eye_lmk_Y_6, eye_lmk_Y_7, eye_lmk_Y_8, eye_lmk_Y_9, eye_lmk_Y_10, eye_lmk_Y_11, eye_lmk_Y_12, eye_lmk_Y_13, eye_lmk_Y_14, eye_lmk_Y_15, eye_lmk_Y_16, eye_lmk_Y_17, eye_lmk_Y_18, eye_lmk_Y_19, eye_lmk_Y_20, eye_lmk_Y_21, eye_lmk_Y_22, eye_lmk_Y_23, eye_lmk_Y_24, eye_lmk_Y_25, eye_lmk_Y_26, eye_lmk_Y_27, eye_lmk_Y_28, eye_lmk_Y_29, eye_lmk_Y_30, eye_lmk_Y_31, eye_lmk_Y_32, eye_lmk_Y_33, eye_lmk_Y_34, eye_lmk_Y_35, eye_lmk_Y_36, eye_lmk_Y_37, eye_lmk_Y_38, eye_lmk_Y_39, eye_lmk_Y_40, eye_lmk_Y_41, eye_lmk_Y_42, eye_lmk_Y_43, eye_lmk_Y_44, eye_lmk_Y_45, eye_lmk_Y_46, eye_lmk_Y_47, eye_lmk_Y_48, eye_lmk_Y_49, eye_lmk_Y_50, eye_lmk_Y_51, eye_lmk_Y_52, eye_lmk_Y_53, eye_lmk_Y_54, eye_lmk_Y_55, eye_lmk_Z_0, eye_lmk_Z_1, eye_lmk_Z_2, eye_lmk_Z_3, eye_lmk_Z_4, eye_lmk_Z_5, eye_lmk_Z_6, eye_lmk_Z_7, eye_lmk_Z_8, eye_lmk_Z_9, eye_lmk_Z_10, eye_lmk_Z_11, eye_lmk_Z_12, eye_lmk_Z_13, eye_lmk_Z_14, eye_lmk_Z_15, eye_lmk_Z_16, eye_lmk_Z_17, eye_lmk_Z_18, eye_lmk_Z_19, eye_lmk_Z_20, eye_lmk_Z_21, eye_lmk_Z_22, eye_lmk_Z_23, eye_lmk_Z_24, eye_lmk_Z_25, eye_lmk_Z_26, eye_lmk_Z_27, eye_lmk_Z_28, eye_lmk_Z_29, eye_lmk_Z_30, eye_lmk_Z_31, eye_lmk_Z_32, eye_lmk_Z_33, eye_lmk_Z_34, eye_lmk_Z_35, eye_lmk_Z_36, eye_lmk_Z_37, eye_lmk_Z_38, eye_lmk_Z_39, eye_lmk_Z_40, eye_lmk_Z_41, eye_lmk_Z_42, eye_lmk_Z_43, eye_lmk_Z_44, eye_lmk_Z_45, eye_lmk_Z_46, eye_lmk_Z_47, eye_lmk_Z_48, eye_lmk_Z_49, eye_lmk_Z_50, eye_lmk_Z_51, eye_lmk_Z_52, eye_lmk_Z_53, eye_lmk_Z_54, eye_lmk_Z_55, pose_Tx, pose_Ty, pose_Tz, pose_Rx, pose_Ry, pose_Rz, x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, x_10, x_11, x_12, x_13, x_14, x_15, x_16, x_17, x_18, x_19, x_20, x_21, x_22, x_23, x_24, x_25, x_26, x_27, x_28, x_29, x_30, x_31, x_32, x_33, x_34, x_35, x_36, x_37, x_38, x_39, x_40, x_41, x_42, x_43, x_44, x_45, x_46, x_47, x_48, x_49, x_50, x_51, x_52, x_53, x_54, x_55, x_56, x_57, x_58, x_59, x_60, x_61, x_62, x_63, x_64, x_65, x_66, x_67, y_0, y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9, y_10, y_11, y_12, y_13, y_14, y_15, y_16, y_17, y_18, y_19, y_20, y_21, y_22, y_23, y_24, y_25, y_26, y_27, y_28, y_29, y_30, y_31, y_32, y_33, y_34, y_35, y_36, y_37, y_38, y_39, y_40, y_41, y_42, y_43, y_44, y_45, y_46, y_47, y_48, y_49, y_50, y_51, y_52, y_53, y_54, y_55, y_56, y_57, y_58, y_59, y_60, y_61, y_62, y_63, y_64, y_65, y_66, y_67, X_0, X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15, X_16, X_17, X_18, X_19, X_20, X_21, X_22, X_23, X_24, X_25, X_26, X_27, X_28, X_29, X_30, X_31, X_32, X_33, X_34, X_35, X_36, X_37, X_38, X_39, X_40, X_41, X_42, X_43, X_44, X_45, X_46, X_47, X_48, X_49, X_50, X_51, X_52, X_53, X_54, X_55, X_56, X_57, X_58, X_59, X_60, X_61, X_62, X_63, X_64, X_65, X_66, X_67, Y_0, Y_1, Y_2, Y_3, Y_4, Y_5, Y_6, Y_7, Y_8, Y_9, Y_10, Y_11, Y_12, Y_13, Y_14, Y_15, Y_16, Y_17, Y_18, Y_19, Y_20, Y_21, Y_22, Y_23, Y_24, Y_25, Y_26, Y_27, Y_28, Y_29, Y_30, Y_31, Y_32, Y_33, Y_34, Y_35, Y_36, Y_37, Y_38, Y_39, Y_40, Y_41, Y_42, Y_43, Y_44, Y_45, Y_46, Y_47, Y_48, Y_49, Y_50, Y_51, Y_52, Y_53, Y_54, Y_55, Y_56, Y_57, Y_58, Y_59, Y_60, Y_61, Y_62, Y_63, Y_64, Y_65, Y_66, Y_67, Z_0, Z_1, Z_2, Z_3, Z_4, Z_5, Z_6, Z_7, Z_8, Z_9, Z_10, Z_11, Z_12, Z_13, Z_14, Z_15, Z_16, Z_17, Z_18, Z_19, Z_20, Z_21, Z_22, Z_23, Z_24, Z_25, Z_26, Z_27, Z_28, Z_29, Z_30, Z_31, Z_32, Z_33, Z_34, Z_35, Z_36, Z_37, Z_38, Z_39, Z_40, Z_41, Z_42, Z_43, Z_44, Z_45, Z_46, Z_47, Z_48, Z_49, Z_50, Z_51, Z_52, Z_53, Z_54, Z_55, Z_56, Z_57, Z_58, Z_59, Z_60, Z_61, Z_62, Z_63, Z_64, Z_65, Z_66, Z_67, p_scale, p_rx, p_ry, p_rz, p_tx, p_ty, p_0, p_1, p_2, p_3, p_4, p_5, p_6, p_7, p_8, p_9, p_10, p_11, p_12, p_13, p_14, p_15, p_16, p_17, p_18, p_19, p_20, p_21, p_22, p_23, p_24, p_25, p_26, p_27, p_28, p_29, p_30, p_31, p_32, p_33, AU01_r, AU02_r, AU04_r, AU05_r, AU06_r, AU07_r, AU09_r, AU10_r, AU12_r, AU14_r, AU15_r, AU17_r, AU20_r, AU23_r, AU25_r, AU26_r, AU45_r, AU01_c, AU02_c, AU04_c, AU05_c, AU06_c, AU07_c, AU09_c, AU10_c, AU12_c, AU14_c, AU15_c, AU17_c, AU20_c, AU23_c, AU25_c, AU26_c, AU28_c, AU45_c"
atypes = types.split(",")
data.columns=atypes

In [87]:
data

,name,face,confidence,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,f360fba6e93c11e1925f22000a1c891a_6.csv,0,0.975,0.044863,0.271647,-0.961351,-0.162479,0.300276,-0.939912,-0.062,...,1,1,1,1,1,0,0,1,0,0
1,ddfdc6a8c45711e2893b22000aa8100d_6.csv,0,0.975,0.003266,0.065706,-0.997834,-0.087321,0.233891,-0.968334,-0.043,...,1,1,0,0,0,0,0,1,1,0
2,f9ab45aee7e511e28b8322000a1f92ef_6.csv,0,0.975,0.045251,0.429472,-0.901946,-0.140996,0.434684,-0.889478,-0.053,...,0,1,0,1,0,0,0,0,0,0
3,10261318_1459268490974406_1363715992_a.csv,0,0.875,0.229777,0.251888,-0.940082,0.023392,0.293294,-0.955736,0.133,...,0,0,0,0,0,0,0,0,0,0
4,d5087146a92211e3a13f12befe090f9c_6.csv,0,0.875,-0.07225,0.171879,-0.982465,-0.268379,0.226164,-0.936388,-0.176,...,1,1,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,a813936cadd911e38e6512353404eac4_6.csv,0,0.875,-0.01994,0.230449,-0.97288,-0.213688,0.247381,-0.945061,-0.121,...,0,1,0,0,1,0,0,1,0,0
224,a6e4c176ab0611e3b1240e2cf5a5d27e_6.csv,0,0.975,0.343518,0.175066,-0.922685,0.135661,0.194438,-0.971488,0.248,...,1,0,0,0,0,0,1,0,0,0
225,e1252d72a44e11e29c4222000a9e071d_6.csv,0,0.875,-0.039491,-0.147589,-0.98826,-0.390052,-0.005823,-0.920775,-0.221,...,0,1,1,1,0,1,0,0,1,0
226,48950752c00011e38b170002c9549942_6.csv,0,0.925,-0.048442,0.618281,-0.784463,-0.116583,0.457376,-0.881598,-0.099,...,0,0,0,0,0,0,0,0,0,1
227,10261319_425246550944834_1629903854_a.csv,0,0.975,0.253983,0.100316,-0.961992,0.071993,0.118444,-0.990347,0.165,...,0,0,0,0,0,0,0,0,0,0

In [88]:

data.columns

Index(['name', 'face', ' confidence', ' gaze_0_x', ' gaze_0_y', ' gaze_0_z',
       ' gaze_1_x', ' gaze_1_y', ' gaze_1_z', ' gaze_angle_x',
       ...
       ' AU12_c', ' AU14_c', ' AU15_c', ' AU17_c', ' AU20_c', ' AU23_c',
       ' AU25_c', ' AU26_c', ' AU28_c', ' AU45_c'],
      dtype='object', length=712)

In [89]:
data.drop(['name', 'face', ' confidence',' eye_lmk_x_0',
 ' eye_lmk_x_1',
 ' eye_lmk_x_2',
 ' eye_lmk_x_3',
 ' eye_lmk_x_4',
 ' eye_lmk_x_5',
 ' eye_lmk_x_6',
 ' eye_lmk_x_7',
 ' eye_lmk_x_8',
 ' eye_lmk_x_9',
 ' eye_lmk_x_10',
 ' eye_lmk_x_11',
 ' eye_lmk_x_12',
 ' eye_lmk_x_13',
 ' eye_lmk_x_14',
 ' eye_lmk_x_15',
 ' eye_lmk_x_16',
 ' eye_lmk_x_17',
 ' eye_lmk_x_18',
 ' eye_lmk_x_19',
 ' eye_lmk_x_20',
 ' eye_lmk_x_21',
 ' eye_lmk_x_22',
 ' eye_lmk_x_23',
 ' eye_lmk_x_24',
 ' eye_lmk_x_25',
 ' eye_lmk_x_26',
 ' eye_lmk_x_27',
 ' eye_lmk_x_28',
 ' eye_lmk_x_29',
 ' eye_lmk_x_30',
 ' eye_lmk_x_31',
 ' eye_lmk_x_32',
 ' eye_lmk_x_33',
 ' eye_lmk_x_34',
 ' eye_lmk_x_35',
 ' eye_lmk_x_36',
 ' eye_lmk_x_37',
 ' eye_lmk_x_38',
 ' eye_lmk_x_39',
 ' eye_lmk_x_40',
 ' eye_lmk_x_41',
 ' eye_lmk_x_42',
 ' eye_lmk_x_43',
 ' eye_lmk_x_44',
 ' eye_lmk_x_45',
 ' eye_lmk_x_46',
 ' eye_lmk_x_47',
 ' eye_lmk_x_48',
 ' eye_lmk_x_49',
 ' eye_lmk_x_50',
 ' eye_lmk_x_51',
 ' eye_lmk_x_52',
 ' eye_lmk_x_53',
 ' eye_lmk_x_54',
 ' eye_lmk_x_55',
 ' eye_lmk_y_0',
 ' eye_lmk_y_1',
 ' eye_lmk_y_2',
 ' eye_lmk_y_3',
 ' eye_lmk_y_4',
 ' eye_lmk_y_5',
 ' eye_lmk_y_6',
 ' eye_lmk_y_7',
 ' eye_lmk_y_8',
 ' eye_lmk_y_9',
 ' eye_lmk_y_10',
 ' eye_lmk_y_11',
 ' eye_lmk_y_12',
 ' eye_lmk_y_13',
 ' eye_lmk_y_14',
 ' eye_lmk_y_15',
 ' eye_lmk_y_16',
 ' eye_lmk_y_17',
 ' eye_lmk_y_18',
 ' eye_lmk_y_19',
 ' eye_lmk_y_20',
 ' eye_lmk_y_21',
 ' eye_lmk_y_22',
 ' eye_lmk_y_23',
 ' eye_lmk_y_24',
 ' eye_lmk_y_25',
 ' eye_lmk_y_26',
 ' eye_lmk_y_27',
 ' eye_lmk_y_28',
 ' eye_lmk_y_29',
 ' eye_lmk_y_30',
 ' eye_lmk_y_31',
 ' eye_lmk_y_32',
 ' eye_lmk_y_33',
 ' eye_lmk_y_34',
 ' eye_lmk_y_35',
 ' eye_lmk_y_36',
 ' eye_lmk_y_37',
 ' eye_lmk_y_38',
 ' eye_lmk_y_39',
 ' eye_lmk_y_40',
 ' eye_lmk_y_41',
 ' eye_lmk_y_42',
 ' eye_lmk_y_43',
 ' eye_lmk_y_44',
 ' eye_lmk_y_45',
 ' eye_lmk_y_46',
 ' eye_lmk_y_47',
 ' eye_lmk_y_48',
 ' eye_lmk_y_49',
 ' eye_lmk_y_50',
 ' eye_lmk_y_51',
 ' eye_lmk_y_52',
 ' eye_lmk_y_53',
 ' eye_lmk_y_54',
 ' eye_lmk_y_55',
 ' eye_lmk_X_0',
 ' eye_lmk_X_1',
 ' eye_lmk_X_2',
 ' eye_lmk_X_3',
 ' eye_lmk_X_4',
 ' eye_lmk_X_5',
 ' eye_lmk_X_6',
 ' eye_lmk_X_7',
 ' eye_lmk_X_8',
 ' eye_lmk_X_9',
 ' eye_lmk_X_10',
 ' eye_lmk_X_11',
 ' eye_lmk_X_12',
 ' eye_lmk_X_13',
 ' eye_lmk_X_14',
 ' eye_lmk_X_15',
 ' eye_lmk_X_16',
 ' eye_lmk_X_17',
 ' eye_lmk_X_18',
 ' eye_lmk_X_19',
 ' eye_lmk_X_20',
 ' eye_lmk_X_21',
 ' eye_lmk_X_22',
 ' eye_lmk_X_23',
 ' eye_lmk_X_24',
 ' eye_lmk_X_25',
 ' eye_lmk_X_26',
 ' eye_lmk_X_27',
 ' eye_lmk_X_28',
 ' eye_lmk_X_29',
 ' eye_lmk_X_30',
 ' eye_lmk_X_31',
 ' eye_lmk_X_32',
 ' eye_lmk_X_33',
 ' eye_lmk_X_34',
 ' eye_lmk_X_35',
 ' eye_lmk_X_36',
 ' eye_lmk_X_37',
 ' eye_lmk_X_38',
 ' eye_lmk_X_39',
 ' eye_lmk_X_40',
 ' eye_lmk_X_41',
 ' eye_lmk_X_42',
 ' eye_lmk_X_43',
 ' eye_lmk_X_44',
 ' eye_lmk_X_45',
 ' eye_lmk_X_46',
 ' eye_lmk_X_47',
 ' eye_lmk_X_48',
 ' eye_lmk_X_49',
 ' eye_lmk_X_50',
 ' eye_lmk_X_51',
 ' eye_lmk_X_52',
 ' eye_lmk_X_53',
 ' eye_lmk_X_54',
 ' eye_lmk_X_55',
 ' eye_lmk_Y_0',
 ' eye_lmk_Y_1',
 ' eye_lmk_Y_2',
 ' eye_lmk_Y_3',
 ' eye_lmk_Y_4',
 ' eye_lmk_Y_5',
 ' eye_lmk_Y_6',
 ' eye_lmk_Y_7',
 ' eye_lmk_Y_8',
 ' eye_lmk_Y_9',
 ' eye_lmk_Y_10',
 ' eye_lmk_Y_11',
 ' eye_lmk_Y_12',
 ' eye_lmk_Y_13',
 ' eye_lmk_Y_14',
 ' eye_lmk_Y_15',
 ' eye_lmk_Y_16',
 ' eye_lmk_Y_17',
 ' eye_lmk_Y_18',
 ' eye_lmk_Y_19',
 ' eye_lmk_Y_20',
 ' eye_lmk_Y_21',
 ' eye_lmk_Y_22',
 ' eye_lmk_Y_23',
 ' eye_lmk_Y_24',
 ' eye_lmk_Y_25',
 ' eye_lmk_Y_26',
 ' eye_lmk_Y_27',
 ' eye_lmk_Y_28',
 ' eye_lmk_Y_29',
 ' eye_lmk_Y_30',
 ' eye_lmk_Y_31',
 ' eye_lmk_Y_32',
 ' eye_lmk_Y_33',
 ' eye_lmk_Y_34',
 ' eye_lmk_Y_35',
 ' eye_lmk_Y_36',
 ' eye_lmk_Y_37',
 ' eye_lmk_Y_38',
 ' eye_lmk_Y_39',
 ' eye_lmk_Y_40',
 ' eye_lmk_Y_41',
 ' eye_lmk_Y_42',
 ' eye_lmk_Y_43',
 ' eye_lmk_Y_44',
 ' eye_lmk_Y_45',
 ' eye_lmk_Y_46',
 ' eye_lmk_Y_47',
 ' eye_lmk_Y_48',
 ' eye_lmk_Y_49',
 ' eye_lmk_Y_50',
 ' eye_lmk_Y_51',
 ' eye_lmk_Y_52',
 ' eye_lmk_Y_53',
 ' eye_lmk_Y_54',
 ' eye_lmk_Y_55',
 ' eye_lmk_Z_0',
 ' eye_lmk_Z_1',
 ' eye_lmk_Z_2',
 ' eye_lmk_Z_3',
 ' eye_lmk_Z_4',
 ' eye_lmk_Z_5',
 ' eye_lmk_Z_6',
 ' eye_lmk_Z_7',
 ' eye_lmk_Z_8',
 ' eye_lmk_Z_9',
 ' eye_lmk_Z_10',
 ' eye_lmk_Z_11',
 ' eye_lmk_Z_12',
 ' eye_lmk_Z_13',
 ' eye_lmk_Z_14',
 ' eye_lmk_Z_15',
 ' eye_lmk_Z_16',
 ' eye_lmk_Z_17',
 ' eye_lmk_Z_18',
 ' eye_lmk_Z_19',
 ' eye_lmk_Z_20',
 ' eye_lmk_Z_21',
 ' eye_lmk_Z_22',
 ' eye_lmk_Z_23',
 ' eye_lmk_Z_24',
 ' eye_lmk_Z_25',
 ' eye_lmk_Z_26',
 ' eye_lmk_Z_27',
 ' eye_lmk_Z_28',
 ' eye_lmk_Z_29',
 ' eye_lmk_Z_30',
 ' eye_lmk_Z_31',
 ' eye_lmk_Z_32',
 ' eye_lmk_Z_33',
 ' eye_lmk_Z_34',
 ' eye_lmk_Z_35',
 ' eye_lmk_Z_36',
 ' eye_lmk_Z_37',
 ' eye_lmk_Z_38',
 ' eye_lmk_Z_39',
 ' eye_lmk_Z_40',
 ' eye_lmk_Z_41',
 ' eye_lmk_Z_42',
 ' eye_lmk_Z_43',
 ' eye_lmk_Z_44',
 ' eye_lmk_Z_45',
 ' eye_lmk_Z_46',
 ' eye_lmk_Z_47',
 ' eye_lmk_Z_48',
 ' eye_lmk_Z_49',
 ' eye_lmk_Z_50',
 ' eye_lmk_Z_51',
 ' eye_lmk_Z_52',
 ' eye_lmk_Z_53',
 ' eye_lmk_Z_54',
 ' eye_lmk_Z_55',
 ' pose_Tx',
 ' pose_Ty',
 ' pose_Tz',
 ' pose_Rx',
 ' pose_Ry',
 ' pose_Rz',
 ' x_0',
 ' x_1',
 ' x_2',
 ' x_3',
 ' x_4',
 ' x_5',
 ' x_6',
 ' x_7',
 ' x_8',
 ' x_9',
 ' x_10',
 ' x_11',
 ' x_12',
 ' x_13',
 ' x_14',
 ' x_15',
 ' x_16',
 ' x_17',
 ' x_18',
 ' x_19',
 ' x_20',
 ' x_21',
 ' x_22',
 ' x_23',
 ' x_24',
 ' x_25',
 ' x_26',
 ' x_27',
 ' x_28',
 ' x_29',
 ' x_30',
 ' x_31',
 ' x_32',
 ' x_33',
 ' x_34',
 ' x_35',
 ' x_36',
 ' x_37',
 ' x_38',
 ' x_39',
 ' x_40',
 ' x_41',
 ' x_42',
 ' x_43',
 ' x_44',
 ' x_45',
 ' x_46',
 ' x_47',
 ' x_48',
 ' x_49',
 ' x_50',
 ' x_51',
 ' x_52',
 ' x_53',
 ' x_54',
 ' x_55',
 ' x_56',
 ' x_57',
 ' x_58',
 ' x_59',
 ' x_60',
 ' x_61',
 ' x_62',
 ' x_63',
 ' x_64',
 ' x_65',
 ' x_66',
 ' x_67',
 ' y_0',
 ' y_1',
 ' y_2',
 ' y_3',
 ' y_4',
 ' y_5',
 ' y_6',
 ' y_7',
 ' y_8',
 ' y_9',
 ' y_10',
 ' y_11',
 ' y_12',
 ' y_13',
 ' y_14',
 ' y_15',
 ' y_16',
 ' y_17',
 ' y_18',
 ' y_19',
 ' y_20',
 ' y_21',
 ' y_22',
 ' y_23',
 ' y_24',
 ' y_25',
 ' y_26',
 ' y_27',
 ' y_28',
 ' y_29',
 ' y_30',
 ' y_31',
 ' y_32',
 ' y_33',
 ' y_34',
 ' y_35',
 ' y_36',
 ' y_37',
 ' y_38',
 ' y_39',
 ' y_40',
 ' y_41',
 ' y_42',
 ' y_43',
 ' y_44',
 ' y_45',
 ' y_46',
 ' y_47',
 ' y_48',
 ' y_49',
 ' y_50',
 ' y_51',
 ' y_52',
 ' y_53',
 ' y_54',
 ' y_55',
 ' y_56',
 ' y_57',
 ' y_58',
 ' y_59',
 ' y_60',
 ' y_61',
 ' y_62',
 ' y_63',
 ' y_64',
 ' y_65',
 ' y_66',
 ' y_67',
 ' X_0',
 ' X_1',
 ' X_2',
 ' X_3',
 ' X_4',
 ' X_5',
 ' X_6',
 ' X_7',
 ' X_8',
 ' X_9',
 ' X_10',
 ' X_11',
 ' X_12',
 ' X_13',
 ' X_14',
 ' X_15',
 ' X_16',
 ' X_17',
 ' X_18',
 ' X_19',
 ' X_20',
 ' X_21',
 ' X_22',
 ' X_23',
 ' X_24',
 ' X_25',
 ' X_26',
 ' X_27',
 ' X_28',
 ' X_29',
 ' X_30',
 ' X_31',
 ' X_32',
 ' X_33',
 ' X_34',
 ' X_35',
 ' X_36',
 ' X_37',
 ' X_38',
 ' X_39',
 ' X_40',
 ' X_41',
 ' X_42',
 ' X_43',
 ' X_44',
 ' X_45',
 ' X_46',
 ' X_47',
 ' X_48',
 ' X_49',
 ' X_50',
 ' X_51',
 ' X_52',
 ' X_53',
 ' X_54',
 ' X_55',
 ' X_56',
 ' X_57',
 ' X_58',
 ' X_59',
 ' X_60',
 ' X_61',
 ' X_62',
 ' X_63',
 ' X_64',
 ' X_65',
 ' X_66',
 ' X_67',
 ' Y_0',
 ' Y_1',
 ' Y_2',
 ' Y_3',
 ' Y_4',
 ' Y_5',
 ' Y_6',
 ' Y_7',
 ' Y_8',
 ' Y_9',
 ' Y_10',
 ' Y_11',
 ' Y_12',
 ' Y_13',
 ' Y_14',
 ' Y_15',
 ' Y_16',
 ' Y_17',
 ' Y_18',
 ' Y_19',
 ' Y_20',
 ' Y_21',
 ' Y_22',
 ' Y_23',
 ' Y_24',
 ' Y_25',
 ' Y_26',
 ' Y_27',
 ' Y_28',
 ' Y_29',
 ' Y_30',
 ' Y_31',
 ' Y_32',
 ' Y_33',
 ' Y_34',
 ' Y_35',
 ' Y_36',
 ' Y_37',
 ' Y_38',
 ' Y_39',
 ' Y_40',
 ' Y_41',
 ' Y_42',
 ' Y_43',
 ' Y_44',
 ' Y_45',
 ' Y_46',
 ' Y_47',
 ' Y_48',
 ' Y_49',
 ' Y_50',
 ' Y_51',
 ' Y_52',
 ' Y_53',
 ' Y_54',
 ' Y_55',
 ' Y_56',
 ' Y_57',
 ' Y_58',
 ' Y_59',
 ' Y_60',
 ' Y_61',
 ' Y_62',
 ' Y_63',
 ' Y_64',
 ' Y_65',
 ' Y_66',
 ' Y_67',
 ' Z_0',
 ' Z_1',
 ' Z_2',
 ' Z_3',
 ' Z_4',
 ' Z_5',
 ' Z_6',
 ' Z_7',
 ' Z_8',
 ' Z_9',
 ' Z_10',
 ' Z_11',
 ' Z_12',
 ' Z_13',
 ' Z_14',
 ' Z_15',
 ' Z_16',
 ' Z_17',
 ' Z_18',
 ' Z_19',
 ' Z_20',
 ' Z_21',
 ' Z_22',
 ' Z_23',
 ' Z_24',
 ' Z_25',
 ' Z_26',
 ' Z_27',
 ' Z_28',
 ' Z_29',
 ' Z_30',
 ' Z_31',
 ' Z_32',
 ' Z_33',
 ' Z_34',
 ' Z_35',
 ' Z_36',
 ' Z_37',
 ' Z_38',
 ' Z_39',
 ' Z_40',
 ' Z_41',
 ' Z_42',
 ' Z_43',
 ' Z_44',
 ' Z_45',
 ' Z_46',
 ' Z_47',
 ' Z_48',
 ' Z_49',
 ' Z_50',
 ' Z_51',
 ' Z_52',
 ' Z_53',
 ' Z_54',
 ' Z_55',
 ' Z_56',
 ' Z_57',
 ' Z_58',
 ' Z_59',
 ' Z_60',
 ' Z_61',
 ' Z_62',
 ' Z_63',
 ' Z_64',
 ' Z_65',
 ' Z_66',
 ' Z_67',
 ' p_scale',
 ' p_rx',
 ' p_ry',
 ' p_rz',
 ' p_tx',
 ' p_ty',
 ' p_0',
 ' p_1',
 ' p_2',
 ' p_3',
 ' p_4',
 ' p_5',
 ' p_6',
 ' p_7',
 ' p_8',
 ' p_9',
 ' p_10',
 ' p_11',
 ' p_12',
 ' p_13',
 ' p_14',
 ' p_15',
 ' p_16',
 ' p_17',
 ' p_18',
 ' p_19',
 ' p_20',
 ' p_21',
 ' p_22',
 ' p_23',
 ' p_24',
 ' p_25',
 ' p_26',
 ' p_27',
 ' p_28',
 ' p_29',
 ' p_30',
 ' p_31',
 ' p_32',
 ' p_33', ' AU12_c', ' AU14_c', ' AU15_c', ' AU17_c', ' AU20_c', ' AU23_c',
       ' AU25_c', ' AU26_c', ' AU28_c', ' AU45_c',' gaze_1_z', ' gaze_angle_x', ' gaze_angle_y', ' AU01_r', ' AU02_r',
       ' AU04_r', ' AU05_r', ' AU06_r', ' AU07_r', ' AU09_r', ' AU10_r',
       ' AU12_r', ' AU14_r', ' AU15_r', ' AU17_r', ' AU20_r', ' AU23_r',
       ' AU25_r', ' AU26_r', ' AU45_r', ' AU01_c', ' AU02_c', ' AU04_c',
       ' AU05_c', ' AU06_c'], axis=1,inplace=True)
data.columns

Index([' gaze_0_x', ' gaze_0_y', ' gaze_0_z', ' gaze_1_x', ' gaze_1_y',
       ' AU07_c', ' AU09_c', ' AU10_c'],
      dtype='object')

In [90]:
data

     gaze_0_x  gaze_0_y  gaze_0_z  gaze_1_x  gaze_1_y  AU07_c  AU09_c  AU10_c
0    0.044863  0.271647 -0.961351 -0.162479  0.300276       1       0       1
1    0.003266  0.065706 -0.997834 -0.087321  0.233891       0       0       1
2    0.045251  0.429472 -0.901946 -0.140996  0.434684       1       0       0
3    0.229777  0.251888 -0.940082  0.023392  0.293294       0       0       0
4    -0.07225  0.171879 -0.982465 -0.268379  0.226164       0       1       1
..        ...       ...       ...       ...       ...     ...     ...     ...
223  -0.01994  0.230449  -0.97288 -0.213688  0.247381       1       0       0
224  0.343518  0.175066 -0.922685  0.135661  0.194438       0       0       1
225 -0.039491 -0.147589  -0.98826 -0.390052 -0.005823       0       1       1
226 -0.048442  0.618281 -0.784463 -0.116583  0.457376       0       0       0
227  0.253983  0.100316 -0.961992  0.071993  0.118444       1       0       0

[228 rows x 8 columns]

In [91]:
array = data.values
array

array([[0.044863, 0.27164699999999997, -0.9613510000000001, ..., 1.0,
        0.0, 1.0],
       [0.003266, 0.065706, -0.997834, ..., 0.0, 0.0, 1.0],
       [0.045251, 0.429472, -0.9019459999999999, ..., 1.0, 0.0, 0.0],
       ...,
       [-0.039491000000000005, -0.147589, -0.98826, ..., 0.0, 1.0, 1.0],
       [-0.048442, 0.6182810000000001, -0.784463, ..., 0.0, 0.0, 0.0],
       [0.253983, 0.100316, -0.961992, ..., 1.0, 0.0, 0.0]], dtype=object)

In [92]:
for i in range(5):
    array[:,i]= array[:,i].astype(float)
    
array

array([[0.044863, 0.27164699999999997, -0.9613510000000001, ..., 1.0,
        0.0, 1.0],
       [0.003266, 0.065706, -0.997834, ..., 0.0, 0.0, 1.0],
       [0.045251, 0.429472, -0.9019459999999999, ..., 1.0, 0.0, 0.0],
       ...,
       [-0.039491000000000005, -0.147589, -0.98826, ..., 0.0, 1.0, 1.0],
       [-0.048442, 0.6182810000000001, -0.784463, ..., 0.0, 0.0, 0.0],
       [0.253983, 0.100316, -0.961992, ..., 1.0, 0.0, 0.0]], dtype=object)

In [93]:
!pip install kmodes

Requirement already satisfied: kmodes in ./opt/anaconda3/lib/python3.7/site-packages (0.10.2)
Requirement already satisfied: numpy>=1.10.4 in ./opt/anaconda3/lib/python3.7/site-packages (from kmodes) (1.18.1)
Requirement already satisfied: joblib>=0.11 in ./opt/anaconda3/lib/python3.7/site-packages (from kmodes) (0.14.1)
Requirement already satisfied: scipy>=0.13.3 in ./opt/anaconda3/lib/python3.7/site-packages (from kmodes) (1.4.1)
Requirement already satisfied: scikit-learn>=0.19.0 in ./opt/anaconda3/lib/python3.7/site-packages (from kmodes) (0.22.1)

In [94]:

import numpy as np
import pandas as pd

from kmodes.kprototypes import KPrototypes

In [95]:
kproto = KPrototypes(n_clusters=3, verbose=2,max_iter=20) 
clusters = kproto.fit_predict(array, categorical=[5, 6, 7])

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 52, ncost: 42.44365859959946
Run: 1, iteration: 2/20, moves: 29, ncost: 39.906550586349525
Run: 1, iteration: 3/20, moves: 1, ncost: 39.905742742995216
Run: 1, iteration: 4/20, moves: 0, ncost: 39.905742742995216
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/20, moves: 44, ncost: 36.88843432782332
Run: 2, iteration: 2/20, moves: 1, ncost: 36.888202922102096
Run: 2, iteration: 3/20, moves: 0, ncost: 36.888202922102096
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/20, moves: 27, ncost: 46.02810611580966
Run: 3, iteration: 2/20, moves: 4, ncost: 46.019510162237125
Run: 3, iteration: 3/20, moves: 0, ncost: 46.019510162237125
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 4, iteration: 1/20, moves: 57, ncost: 42.82088641855893
Run: 4, iteration: 2/20, moves: 7, ncost: 42.78020599037957
Run: 4, iteration: 3/20, moves: 0, ncost: 42.78020599037957
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 5, iteration: 1/20, moves: 45, ncost: 43.11880835672508
Run: 5, iteration: 2/20, moves: 11, ncost: 42.974918828804114
Run: 5, iteration: 3/20, moves: 4, ncost: 42.963862591138735
Run: 5, iteration: 4/20, moves: 1, ncost: 42.961895656954916
Run: 5, iteration: 5/20, moves: 0, ncost: 42.961895656954916
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 6, iteration: 1/20, moves: 48, ncost: 42.44506207650451
Run: 6, iteration: 2/20, moves: 28, ncost: 39.91094682882304
Run: 6, iteration: 3/20, moves: 2, ncost: 39.905742742995216
Run: 6, iteration: 4/20, moves: 0, ncost: 39.905742742995216
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 7, iteration: 1/20, moves: 82, ncost: 37.08069447334525
Run: 7, iteration: 2/20, moves: 11, ncost: 36.933439883831106
Run: 7, iteration: 3/20, moves: 4, ncost: 36.89772560118736
Run: 7, iteration: 4/20, moves: 1, ncost: 36.89586082641663
Run: 7, iteration: 5/20, moves: 0, ncost: 36.89586082641663
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 8, iteration: 1/20, moves: 33, ncost: 37.07047492053142
Run: 8, iteration: 2/20, moves: 8, ncost: 36.920784474353184
Run: 8, iteration: 3/20, moves: 2, ncost: 36.90459696442694
Run: 8, iteration: 4/20, moves: 2, ncost: 36.8902572029944
Run: 8, iteration: 5/20, moves: 0, ncost: 36.8902572029944
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 9, iteration: 1/20, moves: 53, ncost: 46.07016925705694
Run: 9, iteration: 2/20, moves: 10, ncost: 45.96684654636978
Run: 9, iteration: 3/20, moves: 5, ncost: 45.9312488337475
Run: 9, iteration: 4/20, moves: 2, ncost: 45.91893283017353
Run: 9, iteration: 5/20, moves: 0, ncost: 45.91893283017353
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 10, iteration: 1/20, moves: 65, ncost: 39.191859195520756
Run: 10, iteration: 2/20, moves: 8, ncost: 39.066105342393456
Run: 10, iteration: 3/20, moves: 4, ncost: 38.9608207101261
Run: 10, iteration: 4/20, moves: 5, ncost: 38.913424170359704
Run: 10, iteration: 5/20, moves: 0, ncost: 38.913424170359704
Best run was number 2

In [96]:
print(kproto.cluster_centroids_)

[array([[ 0.14136889,  0.30637269, -0.91459392, -0.05849051,  0.31435582],
       [ 0.12201331,  0.21295821, -0.94689731, -0.06897145,  0.21405172],
       [ 0.10019733,  0.25716443, -0.93701157, -0.0976255 ,  0.26641359]]), array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])]

In [97]:
cluster_dict= []
for c in clusters:
    cluster_dict.append(c)

In [98]:
cluster_dict

[0,
 0,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 0,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 2,
 0,
 2,
 1,
 0,
 0,
 2,
 1]

In [99]:
data['cluster']=cluster_dict

In [100]:
data

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,AU07_c,AU09_c,AU10_c,cluster
0,0.044863,0.271647,-0.961351,-0.162479,0.300276,1,0,1,0
1,0.003266,0.065706,-0.997834,-0.087321,0.233891,0,0,1,0
2,0.045251,0.429472,-0.901946,-0.140996,0.434684,1,0,0,1
3,0.229777,0.251888,-0.940082,0.023392,0.293294,0,0,0,2
4,-0.07225,0.171879,-0.982465,-0.268379,0.226164,0,1,1,0
...,...,...,...,...,...,...,...,...,...
223,-0.01994,0.230449,-0.97288,-0.213688,0.247381,1,0,0,1
224,0.343518,0.175066,-0.922685,0.135661,0.194438,0,0,1,0
225,-0.039491,-0.147589,-0.98826,-0.390052,-0.005823,0,1,1,0
226,-0.048442,0.618281,-0.784463,-0.116583,0.457376,0,0,0,2
227,0.253983,0.100316,-0.961992,0.071993,0.118444,1,0,0,1

In [101]:
data[data['cluster']==0].head(10)

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,AU07_c,AU09_c,AU10_c,cluster
0,0.044863,0.271647,-0.961351,-0.162479,0.300276,1,0,1,0
1,0.003266,0.065706,-0.997834,-0.087321,0.233891,0,0,1,0
4,-0.07225,0.171879,-0.982465,-0.268379,0.226164,0,1,1,0
5,0.01858,0.519972,-0.853981,-0.15129,0.470563,1,1,1,0
8,0.201199,0.38124,-0.902317,-0.047035,0.405247,0,0,1,0
9,0.150937,0.350409,-0.924354,-0.065833,0.394153,0,0,1,0
12,-0.12149,0.49248,-0.861803,-0.295781,0.439136,1,1,1,0
17,0.058346,0.529993,-0.845992,-0.111898,0.507235,0,1,1,0
19,0.20486,0.131575,-0.969907,0.029289,0.093269,0,0,1,0
26,0.179694,0.494963,-0.850131,-0.025541,0.519578,0,0,1,0

In [102]:
data[data['cluster']==1].head(10)

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,AU07_c,AU09_c,AU10_c,cluster
2,0.045251,0.429472,-0.901946,-0.140996,0.434684,1,0,0,1
7,0.002379,0.263652,-0.964615,-0.232323,0.324143,1,0,0,1
11,0.10456,0.029386,-0.994084,-0.136759,-0.009768,1,1,1,1
13,0.219574,0.144053,-0.964902,0.028608,0.157409,1,0,0,1
16,0.149767,0.280327,-0.948149,-0.008495,0.264354,1,0,0,1
18,0.276543,0.240966,-0.930301,0.089483,0.189976,1,1,1,1
23,0.236565,-0.086957,-0.967717,0.040412,-0.039128,1,1,0,1
24,0.139997,0.510348,-0.848496,5.1e-05,0.539939,1,0,0,1
27,0.119232,0.222306,-0.967659,-0.065086,0.222601,1,0,0,1
30,0.271447,0.341772,-0.899727,0.109278,0.319197,1,0,0,1

In [103]:
data[data['cluster']==2].head(10)

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,AU07_c,AU09_c,AU10_c,cluster
3,0.229777,0.251888,-0.940082,0.023392,0.293294,0,0,0,2
6,0.205347,0.128525,-0.970213,0.030671,0.150097,0,0,0,2
10,0.147408,0.080033,-0.985832,-0.16738,0.144589,0,0,0,2
14,0.152783,0.572494,-0.805548,-0.202084,0.553948,0,0,0,2
15,0.071454,0.094582,-0.992949,-0.204267,0.217926,0,0,0,2
20,-0.013685,0.370994,-0.928534,-0.210663,0.4128,0,0,0,2
21,0.12885,0.41764,-0.89943,-0.031558,0.440313,0,0,0,2
22,0.134165,-0.070259,-0.988465,-0.109248,0.002364,0,0,0,2
25,0.1678,0.072619,-0.983143,0.016442,0.20695,0,0,0,2
28,0.037249,0.504573,-0.862565,-0.257179,0.7267,0,0,0,2

In [109]:
data_original = pd.DataFrame(merge_values)
types = "name,face, confidence, gaze_0_x, gaze_0_y, gaze_0_z, gaze_1_x, gaze_1_y, gaze_1_z, gaze_angle_x, gaze_angle_y, eye_lmk_x_0, eye_lmk_x_1, eye_lmk_x_2, eye_lmk_x_3, eye_lmk_x_4, eye_lmk_x_5, eye_lmk_x_6, eye_lmk_x_7, eye_lmk_x_8, eye_lmk_x_9, eye_lmk_x_10, eye_lmk_x_11, eye_lmk_x_12, eye_lmk_x_13, eye_lmk_x_14, eye_lmk_x_15, eye_lmk_x_16, eye_lmk_x_17, eye_lmk_x_18, eye_lmk_x_19, eye_lmk_x_20, eye_lmk_x_21, eye_lmk_x_22, eye_lmk_x_23, eye_lmk_x_24, eye_lmk_x_25, eye_lmk_x_26, eye_lmk_x_27, eye_lmk_x_28, eye_lmk_x_29, eye_lmk_x_30, eye_lmk_x_31, eye_lmk_x_32, eye_lmk_x_33, eye_lmk_x_34, eye_lmk_x_35, eye_lmk_x_36, eye_lmk_x_37, eye_lmk_x_38, eye_lmk_x_39, eye_lmk_x_40, eye_lmk_x_41, eye_lmk_x_42, eye_lmk_x_43, eye_lmk_x_44, eye_lmk_x_45, eye_lmk_x_46, eye_lmk_x_47, eye_lmk_x_48, eye_lmk_x_49, eye_lmk_x_50, eye_lmk_x_51, eye_lmk_x_52, eye_lmk_x_53, eye_lmk_x_54, eye_lmk_x_55, eye_lmk_y_0, eye_lmk_y_1, eye_lmk_y_2, eye_lmk_y_3, eye_lmk_y_4, eye_lmk_y_5, eye_lmk_y_6, eye_lmk_y_7, eye_lmk_y_8, eye_lmk_y_9, eye_lmk_y_10, eye_lmk_y_11, eye_lmk_y_12, eye_lmk_y_13, eye_lmk_y_14, eye_lmk_y_15, eye_lmk_y_16, eye_lmk_y_17, eye_lmk_y_18, eye_lmk_y_19, eye_lmk_y_20, eye_lmk_y_21, eye_lmk_y_22, eye_lmk_y_23, eye_lmk_y_24, eye_lmk_y_25, eye_lmk_y_26, eye_lmk_y_27, eye_lmk_y_28, eye_lmk_y_29, eye_lmk_y_30, eye_lmk_y_31, eye_lmk_y_32, eye_lmk_y_33, eye_lmk_y_34, eye_lmk_y_35, eye_lmk_y_36, eye_lmk_y_37, eye_lmk_y_38, eye_lmk_y_39, eye_lmk_y_40, eye_lmk_y_41, eye_lmk_y_42, eye_lmk_y_43, eye_lmk_y_44, eye_lmk_y_45, eye_lmk_y_46, eye_lmk_y_47, eye_lmk_y_48, eye_lmk_y_49, eye_lmk_y_50, eye_lmk_y_51, eye_lmk_y_52, eye_lmk_y_53, eye_lmk_y_54, eye_lmk_y_55, eye_lmk_X_0, eye_lmk_X_1, eye_lmk_X_2, eye_lmk_X_3, eye_lmk_X_4, eye_lmk_X_5, eye_lmk_X_6, eye_lmk_X_7, eye_lmk_X_8, eye_lmk_X_9, eye_lmk_X_10, eye_lmk_X_11, eye_lmk_X_12, eye_lmk_X_13, eye_lmk_X_14, eye_lmk_X_15, eye_lmk_X_16, eye_lmk_X_17, eye_lmk_X_18, eye_lmk_X_19, eye_lmk_X_20, eye_lmk_X_21, eye_lmk_X_22, eye_lmk_X_23, eye_lmk_X_24, eye_lmk_X_25, eye_lmk_X_26, eye_lmk_X_27, eye_lmk_X_28, eye_lmk_X_29, eye_lmk_X_30, eye_lmk_X_31, eye_lmk_X_32, eye_lmk_X_33, eye_lmk_X_34, eye_lmk_X_35, eye_lmk_X_36, eye_lmk_X_37, eye_lmk_X_38, eye_lmk_X_39, eye_lmk_X_40, eye_lmk_X_41, eye_lmk_X_42, eye_lmk_X_43, eye_lmk_X_44, eye_lmk_X_45, eye_lmk_X_46, eye_lmk_X_47, eye_lmk_X_48, eye_lmk_X_49, eye_lmk_X_50, eye_lmk_X_51, eye_lmk_X_52, eye_lmk_X_53, eye_lmk_X_54, eye_lmk_X_55, eye_lmk_Y_0, eye_lmk_Y_1, eye_lmk_Y_2, eye_lmk_Y_3, eye_lmk_Y_4, eye_lmk_Y_5, eye_lmk_Y_6, eye_lmk_Y_7, eye_lmk_Y_8, eye_lmk_Y_9, eye_lmk_Y_10, eye_lmk_Y_11, eye_lmk_Y_12, eye_lmk_Y_13, eye_lmk_Y_14, eye_lmk_Y_15, eye_lmk_Y_16, eye_lmk_Y_17, eye_lmk_Y_18, eye_lmk_Y_19, eye_lmk_Y_20, eye_lmk_Y_21, eye_lmk_Y_22, eye_lmk_Y_23, eye_lmk_Y_24, eye_lmk_Y_25, eye_lmk_Y_26, eye_lmk_Y_27, eye_lmk_Y_28, eye_lmk_Y_29, eye_lmk_Y_30, eye_lmk_Y_31, eye_lmk_Y_32, eye_lmk_Y_33, eye_lmk_Y_34, eye_lmk_Y_35, eye_lmk_Y_36, eye_lmk_Y_37, eye_lmk_Y_38, eye_lmk_Y_39, eye_lmk_Y_40, eye_lmk_Y_41, eye_lmk_Y_42, eye_lmk_Y_43, eye_lmk_Y_44, eye_lmk_Y_45, eye_lmk_Y_46, eye_lmk_Y_47, eye_lmk_Y_48, eye_lmk_Y_49, eye_lmk_Y_50, eye_lmk_Y_51, eye_lmk_Y_52, eye_lmk_Y_53, eye_lmk_Y_54, eye_lmk_Y_55, eye_lmk_Z_0, eye_lmk_Z_1, eye_lmk_Z_2, eye_lmk_Z_3, eye_lmk_Z_4, eye_lmk_Z_5, eye_lmk_Z_6, eye_lmk_Z_7, eye_lmk_Z_8, eye_lmk_Z_9, eye_lmk_Z_10, eye_lmk_Z_11, eye_lmk_Z_12, eye_lmk_Z_13, eye_lmk_Z_14, eye_lmk_Z_15, eye_lmk_Z_16, eye_lmk_Z_17, eye_lmk_Z_18, eye_lmk_Z_19, eye_lmk_Z_20, eye_lmk_Z_21, eye_lmk_Z_22, eye_lmk_Z_23, eye_lmk_Z_24, eye_lmk_Z_25, eye_lmk_Z_26, eye_lmk_Z_27, eye_lmk_Z_28, eye_lmk_Z_29, eye_lmk_Z_30, eye_lmk_Z_31, eye_lmk_Z_32, eye_lmk_Z_33, eye_lmk_Z_34, eye_lmk_Z_35, eye_lmk_Z_36, eye_lmk_Z_37, eye_lmk_Z_38, eye_lmk_Z_39, eye_lmk_Z_40, eye_lmk_Z_41, eye_lmk_Z_42, eye_lmk_Z_43, eye_lmk_Z_44, eye_lmk_Z_45, eye_lmk_Z_46, eye_lmk_Z_47, eye_lmk_Z_48, eye_lmk_Z_49, eye_lmk_Z_50, eye_lmk_Z_51, eye_lmk_Z_52, eye_lmk_Z_53, eye_lmk_Z_54, eye_lmk_Z_55, pose_Tx, pose_Ty, pose_Tz, pose_Rx, pose_Ry, pose_Rz, x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, x_10, x_11, x_12, x_13, x_14, x_15, x_16, x_17, x_18, x_19, x_20, x_21, x_22, x_23, x_24, x_25, x_26, x_27, x_28, x_29, x_30, x_31, x_32, x_33, x_34, x_35, x_36, x_37, x_38, x_39, x_40, x_41, x_42, x_43, x_44, x_45, x_46, x_47, x_48, x_49, x_50, x_51, x_52, x_53, x_54, x_55, x_56, x_57, x_58, x_59, x_60, x_61, x_62, x_63, x_64, x_65, x_66, x_67, y_0, y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9, y_10, y_11, y_12, y_13, y_14, y_15, y_16, y_17, y_18, y_19, y_20, y_21, y_22, y_23, y_24, y_25, y_26, y_27, y_28, y_29, y_30, y_31, y_32, y_33, y_34, y_35, y_36, y_37, y_38, y_39, y_40, y_41, y_42, y_43, y_44, y_45, y_46, y_47, y_48, y_49, y_50, y_51, y_52, y_53, y_54, y_55, y_56, y_57, y_58, y_59, y_60, y_61, y_62, y_63, y_64, y_65, y_66, y_67, X_0, X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15, X_16, X_17, X_18, X_19, X_20, X_21, X_22, X_23, X_24, X_25, X_26, X_27, X_28, X_29, X_30, X_31, X_32, X_33, X_34, X_35, X_36, X_37, X_38, X_39, X_40, X_41, X_42, X_43, X_44, X_45, X_46, X_47, X_48, X_49, X_50, X_51, X_52, X_53, X_54, X_55, X_56, X_57, X_58, X_59, X_60, X_61, X_62, X_63, X_64, X_65, X_66, X_67, Y_0, Y_1, Y_2, Y_3, Y_4, Y_5, Y_6, Y_7, Y_8, Y_9, Y_10, Y_11, Y_12, Y_13, Y_14, Y_15, Y_16, Y_17, Y_18, Y_19, Y_20, Y_21, Y_22, Y_23, Y_24, Y_25, Y_26, Y_27, Y_28, Y_29, Y_30, Y_31, Y_32, Y_33, Y_34, Y_35, Y_36, Y_37, Y_38, Y_39, Y_40, Y_41, Y_42, Y_43, Y_44, Y_45, Y_46, Y_47, Y_48, Y_49, Y_50, Y_51, Y_52, Y_53, Y_54, Y_55, Y_56, Y_57, Y_58, Y_59, Y_60, Y_61, Y_62, Y_63, Y_64, Y_65, Y_66, Y_67, Z_0, Z_1, Z_2, Z_3, Z_4, Z_5, Z_6, Z_7, Z_8, Z_9, Z_10, Z_11, Z_12, Z_13, Z_14, Z_15, Z_16, Z_17, Z_18, Z_19, Z_20, Z_21, Z_22, Z_23, Z_24, Z_25, Z_26, Z_27, Z_28, Z_29, Z_30, Z_31, Z_32, Z_33, Z_34, Z_35, Z_36, Z_37, Z_38, Z_39, Z_40, Z_41, Z_42, Z_43, Z_44, Z_45, Z_46, Z_47, Z_48, Z_49, Z_50, Z_51, Z_52, Z_53, Z_54, Z_55, Z_56, Z_57, Z_58, Z_59, Z_60, Z_61, Z_62, Z_63, Z_64, Z_65, Z_66, Z_67, p_scale, p_rx, p_ry, p_rz, p_tx, p_ty, p_0, p_1, p_2, p_3, p_4, p_5, p_6, p_7, p_8, p_9, p_10, p_11, p_12, p_13, p_14, p_15, p_16, p_17, p_18, p_19, p_20, p_21, p_22, p_23, p_24, p_25, p_26, p_27, p_28, p_29, p_30, p_31, p_32, p_33, AU01_r, AU02_r, AU04_r, AU05_r, AU06_r, AU07_r, AU09_r, AU10_r, AU12_r, AU14_r, AU15_r, AU17_r, AU20_r, AU23_r, AU25_r, AU26_r, AU45_r, AU01_c, AU02_c, AU04_c, AU05_c, AU06_c, AU07_c, AU09_c, AU10_c, AU12_c, AU14_c, AU15_c, AU17_c, AU20_c, AU23_c, AU25_c, AU26_c, AU28_c, AU45_c"
atypes = types.split(",")
data_original.columns=atypes
data_original['cluster']=cluster_dict
data_original

,name,face,confidence,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,cluster
0,f360fba6e93c11e1925f22000a1c891a_6.csv,0,0.975,0.044863,0.271647,-0.961351,-0.162479,0.300276,-0.939912,-0.062,...,1,1,1,1,0,0,1,0,0,0
1,ddfdc6a8c45711e2893b22000aa8100d_6.csv,0,0.975,0.003266,0.065706,-0.997834,-0.087321,0.233891,-0.968334,-0.043,...,1,0,0,0,0,0,1,1,0,0
2,f9ab45aee7e511e28b8322000a1f92ef_6.csv,0,0.975,0.045251,0.429472,-0.901946,-0.140996,0.434684,-0.889478,-0.053,...,1,0,1,0,0,0,0,0,0,1
3,10261318_1459268490974406_1363715992_a.csv,0,0.875,0.229777,0.251888,-0.940082,0.023392,0.293294,-0.955736,0.133,...,0,0,0,0,0,0,0,0,0,2
4,d5087146a92211e3a13f12befe090f9c_6.csv,0,0.875,-0.07225,0.171879,-0.982465,-0.268379,0.226164,-0.936388,-0.176,...,1,1,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,a813936cadd911e38e6512353404eac4_6.csv,0,0.875,-0.01994,0.230449,-0.97288,-0.213688,0.247381,-0.945061,-0.121,...,1,0,0,1,0,0,1,0,0,1
224,a6e4c176ab0611e3b1240e2cf5a5d27e_6.csv,0,0.975,0.343518,0.175066,-0.922685,0.135661,0.194438,-0.971488,0.248,...,0,0,0,0,0,1,0,0,0,0
225,e1252d72a44e11e29c4222000a9e071d_6.csv,0,0.875,-0.039491,-0.147589,-0.98826,-0.390052,-0.005823,-0.920775,-0.221,...,1,1,1,0,1,0,0,1,0,0
226,48950752c00011e38b170002c9549942_6.csv,0,0.925,-0.048442,0.618281,-0.784463,-0.116583,0.457376,-0.881598,-0.099,...,0,0,0,0,0,0,0,0,1,2
227,10261319_425246550944834_1629903854_a.csv,0,0.975,0.253983,0.100316,-0.961992,0.071993,0.118444,-0.990347,0.165,...,0,0,0,0,0,0,0,0,0,1

In [111]:
data_original[data_original['cluster']==0].head(10)

,name,face,confidence,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,cluster
0,f360fba6e93c11e1925f22000a1c891a_6.csv,0,0.975,0.044863,0.271647,-0.961351,-0.162479,0.300276,-0.939912,-0.062,...,1,1,1,1,0,0,1,0,0,0
1,ddfdc6a8c45711e2893b22000aa8100d_6.csv,0,0.975,0.003266,0.065706,-0.997834,-0.087321,0.233891,-0.968334,-0.043,...,1,0,0,0,0,0,1,1,0,0
4,d5087146a92211e3a13f12befe090f9c_6.csv,0,0.875,-0.07225,0.171879,-0.982465,-0.268379,0.226164,-0.936388,-0.176,...,1,1,1,0,0,1,0,0,0,0
5,f6da336634f811e3b88822000a9f1947_6.csv,0,0.925,0.01858,0.519972,-0.853981,-0.15129,0.470563,-0.869299,-0.077,...,1,1,0,0,1,1,0,0,0,0
8,e4cef414ad4211e380770e881b7f4bd6_6.csv,0,0.975,0.201199,0.38124,-0.902317,-0.047035,0.405247,-0.912996,0.085,...,1,0,0,1,0,1,0,0,0,0
9,ea675100b49f11e3b7550e958fbdfd31_6.csv,0,0.975,0.150937,0.350409,-0.924354,-0.065833,0.394153,-0.916684,0.046,...,1,0,0,0,0,1,0,0,1,0
12,e4f390bab23a11e39b0b120baf64fd93_6.csv,0,0.975,-0.12149,0.49248,-0.861803,-0.295781,0.439136,-0.848335,-0.239,...,1,1,0,0,0,0,0,0,0,0
17,dff00d446b4211e3bb7f12119c4bc50d_6.csv,0,0.975,0.058346,0.529993,-0.845992,-0.111898,0.507235,-0.854513,-0.031,...,1,1,1,1,0,1,0,0,1,0
19,10261326_432330540237138_2076014039_a.csv,0,0.825,0.20486,0.131575,-0.969907,0.029289,0.093269,-0.99521,0.119,...,1,0,0,0,0,0,0,0,0,0
26,ebb297ba2c3511e3a91a22000a9e089b_6.csv,0,0.975,0.179694,0.494963,-0.850131,-0.025541,0.519578,-0.854041,0.09,...,1,0,1,0,0,0,0,0,0,0

In [112]:
data_original[data_original['cluster']==1].head(10)

,name,face,confidence,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,cluster
2,f9ab45aee7e511e28b8322000a1f92ef_6.csv,0,0.975,0.045251,0.429472,-0.901946,-0.140996,0.434684,-0.889478,-0.053,...,1,0,1,0,0,0,0,0,0,1
7,a50d85c2a17411e38b2812cb779e5d54_6.csv,0,0.975,0.002379,0.263652,-0.964615,-0.232323,0.324143,-0.917037,-0.122,...,1,0,1,0,0,0,0,0,0,1
11,e17dc84ed16511e2b05122000a1f92cb_6.csv,0,0.975,0.10456,0.029386,-0.994084,-0.136759,-0.009768,-0.990556,-0.016,...,1,0,0,1,1,1,1,0,0,1
13,addacd880c9911e3b5c5123139255467_6.csv,0,0.975,0.219574,0.144053,-0.964902,0.028608,0.157409,-0.987119,0.126,...,1,0,0,1,0,0,0,0,0,1
16,de9e6ee0b6d411e28c4722000a9f1966_6.csv,0,0.975,0.149767,0.280327,-0.948149,-0.008495,0.264354,-0.964388,0.074,...,0,0,0,1,0,1,0,0,0,1
18,a4e4e282bff811e393660002c9c60652_6.csv,0,0.975,0.276543,0.240966,-0.930301,0.089483,0.189976,-0.977702,0.19,...,1,1,0,0,0,1,0,1,0,1
23,10261322_230804903781764_103519379_a.csv,0,0.875,0.236565,-0.086957,-0.967717,0.040412,-0.039128,-0.998417,0.14,...,1,1,1,0,1,0,0,0,1,1
24,10261318_229024980638269_700370021_a.csv,0,0.975,0.139997,0.510348,-0.848496,5.1e-05,0.539939,-0.841704,0.083,...,0,1,0,0,0,0,0,1,0,1
27,d17fc128a83d11e2a07422000a1fab83_6.csv,0,0.975,0.119232,0.222306,-0.967659,-0.065086,0.222601,-0.972735,0.028,...,1,1,1,1,0,0,0,0,0,1
30,d1d6896ab29e11e391a0122461161ebf_6.csv,0,0.975,0.271447,0.341772,-0.899727,0.109278,0.319197,-0.941367,0.204,...,1,1,1,0,0,0,0,0,0,1

In [113]:
data_original[data_original['cluster']==2].head(10)

,name,face,confidence,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,cluster
3,10261318_1459268490974406_1363715992_a.csv,0,0.875,0.229777,0.251888,-0.940082,0.023392,0.293294,-0.955736,0.133,...,0,0,0,0,0,0,0,0,0,2
6,fed5374e66d211e3ad1e12ed570e9379_6.csv,0,0.875,0.205347,0.128525,-0.970213,0.030671,0.150097,-0.988195,0.12,...,0,0,0,0,0,0,1,0,1,2
10,c2151f6ab4a011e3a5870ad1d5d3af2d_6.csv,0,0.875,0.147408,0.080033,-0.985832,-0.16738,0.144589,-0.975232,-0.01,...,0,1,0,0,0,0,0,1,0,2
14,ba54bc4c6c2e11e2b0f722000a9f18db_6.csv,0,0.825,0.152783,0.572494,-0.805548,-0.202084,0.553948,-0.807653,-0.031,...,0,0,0,0,0,0,0,1,0,2
15,e2ddf10ef59c11e29a9d22000a1f979c_6.csv,0,0.925,0.071454,0.094582,-0.992949,-0.204267,0.217926,-0.95435,-0.068,...,1,1,0,1,0,0,0,0,1,2
20,fc69db06679811e3ba760e239e53382e_6.csv,0,0.925,-0.013685,0.370994,-0.928534,-0.210663,0.4128,-0.886125,-0.123,...,0,0,0,0,1,0,0,1,0,2
21,a362c2862ab511e391bd22000a1fbf1d_6.csv,0,0.975,0.12885,0.41764,-0.89943,-0.031558,0.440313,-0.89729,0.054,...,0,1,0,0,0,0,0,0,0,2
22,e8ae93f017f111e39ade22000a1f9bd0_6.csv,0,0.875,0.134165,-0.070259,-0.988465,-0.109248,0.002364,-0.994012,0.013,...,0,0,0,0,0,0,1,0,0,2
25,c2eed828b38811e2bf9022000a1fb723_6.csv,0,0.825,0.1678,0.072619,-0.983143,0.016442,0.20695,-0.978213,0.094,...,0,0,1,0,0,0,0,1,1,2
28,d8862fec26c911e3a0b722000ae911ee_6.csv,0,0.925,0.037249,0.504573,-0.862565,-0.257179,0.7267,-0.636997,-0.146,...,0,1,0,0,0,1,0,1,0,2